### ISSUE TITLE
Score variation between float32 and bfloat16 usage

### ISSUE THREAD

**Issue by vegarab** [ahans30/Binoculars#19] opened 2024-07-31 10:22 UTC
Hi,

Thank you all for this great project, really loving it!

While experimenting with the models, I've encountered a slight hiccup where the results vary quite drastically (>15% in some cases) based on what precision the models are loaded with. 
From your source-code here, the default is to load the models using `torch.bfloat16`. However, when loading in `torch.float32`, which is the fallback, the results are not constant. Scores vary by up to 15% from run-to-run, with identical inputs. This leads to the results not being deterministic, but it also leads to lower reliability and accuracy since the prediction becomes a coin-flip when the scores are within 15% of the thresholds. 

I wanted to point this out, and verify that the tuning of the thresholds were done using `torch.bfloat16`. I believe we would need to decide on different thresholds for `torch.float32`, and even then expect lower accuracy due to the undeterministic results.

**Comment by ahans30** [comment] 2024-07-31 10:49
Thank you, I'm glad you're liking this project.

Non determinism is a known phenomena when working with CUDA cores (see [pytorch doc on reproducibility](https://pytorch.org/docs/stable/notes/randomness.html)). 

All our experiments (including choosing thresholds) on datasets in paper are run at bfloat16 and are in fact reproducible. Since this is a research repo, any downstream user is expected to use their own threshold on relevant datasets at preferred precision.

In order to make scores reproducible using float32 on your end, you can try flipping flag `torch.backends.cudnn.deterministic = True`. In any case, what you're reporting is not stemming from this repo's functionality but from stochastic properties of CUDA/GPUs -- so I'll be closing this issue here.

**Closed as completed by ahans30** 2024-07-31 10:49 UTC

**Comment by vegarab** [comment] 2024-07-31 10:53
Thanks for the prompt reply. 

Indeed, bfloat16 usage is reproducible. 

I am aware of cudnn requiring that flag to be enabled to ensure deterministic outputs, thanks for pointing that out. Mainly I've not been running this on CUDA/GPUs, but rather directly on an ARM-based CPU, including AWS Graviton instances. 

This is where I encounter the lack of deterministic results -- this might then be a product of the instruction set of those ARM CPUs using float32? I haven't verified if this persists on x86 CPUs using float32. 

Thanks for clarifying that all your testing and tuning has been done using bfloat16.
